"""
Stage 1 preprocessing: for one annotation method (threshold_based or model_based),
iterate every participant, annotate every panel that survives the existing
accuracy+NaN-ratio eye-selection policy (ParticipantGazeDataManager.prepare_gaze_data_for_preprocessing
- unchanged logic, just consumed here), save one CSV per panel into a
SDMT_annotated_gaze_<date>_<method> folder (pipeline_config.annotated_gaze_dir), and log
every exclusion (participant/panel/eye + reason) to exclusion_log.csv in that same folder.

Replaces the hardcoded, threshold_based-only notebook cell in
low_level_features_analysis.ipynb with a reusable, resumable, both-methods script.

Resumable: re-running with the same method+date skips participants already recorded in
processed_participants.csv (kept separate from exclusion_log.csv since a fully-clean
participant with zero exclusions would never otherwise appear anywhere on disk).
"""
import glob
import os
import sys
import time
import traceback

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import cv2

from constants import KEY_ANALYSIS_EYE, KEY_TASK_PANEL_IMG, SACCADE_IDX, SCREEN_SIZE
from exclusion_policy import load_manually_excluded_participants, load_tobii_sucks_excluded_participants
from participant_gaze_data_manager import ParticipantGazeDataManager
from pipeline_config import (DICTIONARY_BOUNDARY_RATIO, EXCLUDE_TOBII_SUCKS, MAX_SACCADE_FRACTION,
                              TEXT_BOUNDARY_RATIO, annotated_gaze_dir, main_data_path)


def iter_all_subject_dirs(data_path, groups=("HC", "pwMS")):
    """All participant dirs with an SDMT folder. DONTUSE is always skipped (unrelated
    manual flag). Tobii_Sucks is skipped only if EXCLUDE_TOBII_SUCKS is enabled - unlike
    calibration_drift_qa._iter_subject_dirs, which always skips them; this stage wants
    that as a controllable, currently-disabled option."""
    tobii_sucks_excluded = load_tobii_sucks_excluded_participants() if EXCLUDE_TOBII_SUCKS else set()
    for group in groups:
        for subject_dir in sorted(glob.glob(os.path.join(data_path, group, "*"))):
            if not os.path.isdir(subject_dir):
                continue
            name = os.path.basename(subject_dir)
            if "DONTUSE" in name.upper():
                continue
            if name in tobii_sucks_excluded:
                continue
            if "SDMT" not in os.listdir(subject_dir):
                continue
            yield group, subject_dir


def _panel_load_error_rows(participant, group, entries):
    """Flatten ParticipantGazeDataManager.panel_load_errors entries (one dict per
    dropped panel of an otherwise-successful event) into exclusion_log rows."""
    rows = []
    for e in entries:
        rows.append({
            "participant": participant, "group": group, "panel": e.get("panel"),
            "reason": e.get("error"), "l_acc": e.get("l_acc"), "r_acc": e.get("r_acc"),
            "l_nan_pct": e.get("l_nan_pct"), "r_nan_pct": e.get("r_nan_pct"),
            "other_errors": e.get("other_errors"), "scope": "panel_dropped_from_event",
        })
    return rows


def _event_load_error_rows(participant, group, entries):
    """Flatten ParticipantGazeDataManager.load_errors entries. Each is either a whole
    calibration-event parse/load failure (just an 'error' string), or an
    EventExcludedError with 'panel_details' (same per-panel breakdown as panel_load_errors,
    but for an event where NO panel qualified at all)."""
    rows = []
    for e in entries:
        panel_details = e.get("panel_details")
        if panel_details:
            for pd_ in panel_details:
                rows.append({
                    "participant": participant, "group": group, "panel": pd_.get("panel"),
                    "reason": pd_.get("error"), "l_acc": pd_.get("l_acc"), "r_acc": pd_.get("r_acc"),
                    "l_nan_pct": pd_.get("l_nan_pct"), "r_nan_pct": pd_.get("r_nan_pct"),
                    "other_errors": pd_.get("other_errors"), "scope": "whole_event_excluded",
                })
        else:
            rows.append({
                "participant": participant, "group": group, "panel": None,
                "reason": e.get("error"), "l_acc": None, "r_acc": None,
                "l_nan_pct": None, "r_nan_pct": None, "other_errors": None,
                "scope": "load_error",
            })
    return rows


def run(method, date_str=None):
    data_path = main_data_path()
    out_dir = annotated_gaze_dir(method, date_str)
    os.makedirs(out_dir, exist_ok=True)

    readme_path = os.path.join(out_dir, "README.txt")
    if not os.path.exists(readme_path):
        with open(readme_path, "w") as f:
            f.write(
                f"Generated by run_preprocessing.py:run('{method}').\n\n"
                f"One CSV per participant/panel that passed the accuracy+NaN-ratio "
                f"eye-selection policy (ParticipantGazeDataManager.prepare_gaze_data_for_preprocessing), "
                f"annotated with annotation_method='{method}' "
                f"(ParticipantGazeDataManager.annotate_gaze_events).\n"
                f"Layout: <group>/<participant>/panel_<panel>_annotated_gaze_data.csv, "
                f"columns t,eye_horizontal,eye_vertical,status,evt.\n\n"
                f"exclusion_log.csv: every participant/panel/event excluded during this run, and why.\n"
                f"processed_participants.csv: resume manifest, not analysis output.\n"
            )

    exclusion_csv = os.path.join(out_dir, "exclusion_log.csv")
    manifest_csv = os.path.join(out_dir, "processed_participants.csv")

    done = set()
    if os.path.exists(manifest_csv):
        done = set(pd.read_csv(manifest_csv)["participant"].unique())
        print(f"resuming: {len(done)} participants already processed for {method}")

    exclusion_write_header = not os.path.exists(exclusion_csv)
    manifest_write_header = not os.path.exists(manifest_csv)

    manually_excluded = load_manually_excluded_participants()

    t_start = time.time()
    n_participants_done = 0
    n_panels_saved = 0
    for group, subject_dir in iter_all_subject_dirs(data_path):
        participant = os.path.basename(subject_dir)
        if participant in done:
            continue

        if participant in manually_excluded:
            pd.DataFrame([{
                "participant": participant, "group": group, "panel": None,
                "reason": f"manually_excluded: {manually_excluded[participant]}",
                "l_acc": None, "r_acc": None, "l_nan_pct": None, "r_nan_pct": None,
                "other_errors": None, "scope": "manual_exclusion",
            }]).to_csv(exclusion_csv, mode="a", header=exclusion_write_header, index=False)
            exclusion_write_header = False
            pd.DataFrame([{"participant": participant}]).to_csv(manifest_csv, mode="a", header=manifest_write_header, index=False)
            manifest_write_header = False
            continue

        exclusion_rows = []
        try:
            sd = ParticipantGazeDataManager(subject_dir, data_path, "SDMT", group)
        except Exception as e:
            exclusion_rows.append({
                "participant": participant, "group": group, "panel": None,
                "reason": f"failed to load: {e}", "l_acc": None, "r_acc": None,
                "l_nan_pct": None, "r_nan_pct": None, "other_errors": None,
                "scope": "participant_load_error",
            })
            pd.DataFrame(exclusion_rows).to_csv(exclusion_csv, mode="a", header=exclusion_write_header, index=False)
            exclusion_write_header = False
            pd.DataFrame([{"participant": participant}]).to_csv(manifest_csv, mode="a", header=manifest_write_header, index=False)
            manifest_write_header = False
            continue

        exclusion_rows.extend(_panel_load_error_rows(participant, group, sd.panel_load_errors))
        exclusion_rows.extend(_event_load_error_rows(participant, group, sd.load_errors))

        for panel in list(sd.matched_data.keys()):
            try:
                annotated = sd.annotate_gaze_events(panel, method)
            except Exception:
                exclusion_rows.append({
                    "participant": participant, "group": group, "panel": panel,
                    "reason": f"annotate_gaze_events({method}) raised: {traceback.format_exc(limit=1)}",
                    "l_acc": None, "r_acc": None, "l_nan_pct": None, "r_nan_pct": None,
                    "other_errors": None, "scope": "annotation_error",
                })
                continue

            eye_used = sd.matched_data[panel].get(KEY_ANALYSIS_EYE)

            # Decision 2026-09-22: exclude a panel outright if the annotated stream is
            # mostly saccades - not a real eye-movement pattern, a sign of tracking
            # noise/mislabeling swamping the panel.
            saccade_frac = (annotated["evt"] == SACCADE_IDX).mean() if len(annotated) else 0.0
            if saccade_frac > MAX_SACCADE_FRACTION:
                exclusion_rows.append({
                    "participant": participant, "group": group, "panel": panel,
                    "reason": f"panel {panel}: {saccade_frac:.1%} of samples are saccades "
                              f"(>= {MAX_SACCADE_FRACTION:.0%} threshold)",
                    "l_acc": None, "r_acc": None, "l_nan_pct": None, "r_nan_pct": None,
                    "other_errors": None, "scope": "excess_saccade_fraction",
                })
                continue

            # Decision 2026-09-22: exclude a panel if gaze never registers inside the
            # dictionary/legend area at all - either a compressed/miscalibrated mapping
            # (see the after_analysis_quality_checks_17_09_26 LY082 investigation, where
            # recorded y never dropped below ~0.34, well short of DICTIONARY_BOUNDARY_RATIO)
            # or a genuine gap; either way the resulting search/sequence data is meaningless.
            if (annotated["eye_vertical"] < DICTIONARY_BOUNDARY_RATIO).sum() == 0:
                exclusion_rows.append({
                    "participant": participant, "group": group, "panel": panel,
                    "reason": f"panel {panel}: gaze never registers inside the dictionary/legend "
                              f"area (y never < {DICTIONARY_BOUNDARY_RATIO})",
                    "l_acc": None, "r_acc": None, "l_nan_pct": None, "r_nan_pct": None,
                    "other_errors": None, "scope": "never_visits_dictionary",
                })
                continue

            # Mirror case: gaze never reaches the search-text grid, staying confined to
            # the dictionary/buffer area for the whole panel.
            if (annotated["eye_vertical"] >= TEXT_BOUNDARY_RATIO).sum() == 0:
                exclusion_rows.append({
                    "participant": participant, "group": group, "panel": panel,
                    "reason": f"panel {panel}: gaze never registers inside the search-text area "
                              f"(y never >= {TEXT_BOUNDARY_RATIO})",
                    "l_acc": None, "r_acc": None, "l_nan_pct": None, "r_nan_pct": None,
                    "other_errors": None, "scope": "never_visits_text",
                })
                continue

            # Exclude a panel if gaze never actually lands within the DISPLAYED panel
            # image itself (e.g. consistently off to one side in the letterboxed padding
            # prepare_image_and_gaze adds) - a stricter, position-aware check than the
            # raw [0,1] screen-normalized out-of-range policy, which would not catch
            # samples that are on-screen but off the actual panel content.
            img_path = sd.matched_data[panel].get(KEY_TASK_PANEL_IMG)
            on_panel = True
            if img_path:
                img = cv2.imread(img_path)
                if img is not None:
                    img_height, img_width = img.shape[:2]
                    scale = SCREEN_SIZE[0] / img_height
                    new_width = img_width * scale
                    x_offset = (SCREEN_SIZE[1] - new_width) / 2
                    px = annotated["eye_horizontal"] * SCREEN_SIZE[1]
                    on_panel = bool(((px >= x_offset) & (px <= x_offset + new_width)).any())
            if not on_panel:
                exclusion_rows.append({
                    "participant": participant, "group": group, "panel": panel,
                    "reason": f"panel {panel}: gaze never lands within the displayed panel "
                              f"image itself (always off to one side)",
                    "l_acc": None, "r_acc": None, "l_nan_pct": None, "r_nan_pct": None,
                    "other_errors": None, "scope": "never_on_panel_image",
                })
                continue

            participant_out_dir = os.path.join(out_dir, group, participant)
            os.makedirs(participant_out_dir, exist_ok=True)
            fname = f"panel_{panel}_annotated_gaze_data.csv"
            annotated.to_csv(os.path.join(participant_out_dir, fname), index=False)
            n_panels_saved += 1
            print(f"  {participant}/{panel} (eye={eye_used}) -> {fname}")

        if exclusion_rows:
            pd.DataFrame(exclusion_rows).to_csv(exclusion_csv, mode="a", header=exclusion_write_header, index=False)
            exclusion_write_header = False

        pd.DataFrame([{"participant": participant}]).to_csv(manifest_csv, mode="a", header=manifest_write_header, index=False)
        manifest_write_header = False
        n_participants_done += 1
        if n_participants_done % 10 == 0:
            print(f"... {n_participants_done} participants, {n_panels_saved} panels saved, "
                  f"elapsed={time.time()-t_start:.0f}s")

    print(f"\ndone. method={method} participants this run={n_participants_done} "
          f"panels saved={n_panels_saved} time={time.time()-t_start:.0f}s")
    print(f"output: {out_dir}")


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] not in ("threshold_based", "model_based"):
        print("usage: python run_preprocessing.py <threshold_based|model_based> [date_str]")
        sys.exit(1)
    method_arg = sys.argv[1]
    date_arg = sys.argv[2] if len(sys.argv) > 2 else None
    run(method_arg, date_arg)
